spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,slf4j  #sql
      stat-view-servlet:  #开启监控页功能
        login-username: root
        login-password: 123456
        enabled: true
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:  #对上面的详细配置
        stat:
          enabled: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          throw-exception: true
          config: #不许删表
            drop-table-allow: false
